# Julia and mathematics

Dr. Sandeep Nagar, $3^{rd}$ September $2017$, e-mail: sandeep.nagar@gmail.com

## Types of numbers

* Integers (Int8,Int16,Int32,Int64,Int128)
* Floating point numbers (Float16,Float32,Float64,Float128)
* Complex numbers (real and imaginary parts are either integers or complex)
* Rational numbers (Numerator and denominator are either integers or complex)

### Integers and Floats

In [181]:
a = 2.5 # Lets define a number

2.5

In [182]:
typeof(a) # Type of 'a'

Float64

In [183]:
Int8(a) # Converting it into a integer

LoadError: InexactError()

In [184]:
b=Float16(a) # changing precision

Float16(2.5)

In [185]:
typeof(b) # verifying change of precision

Float16

In [186]:
a = 2 # Defining an integer

2

In [187]:
typeof(a) # Precision of integer strorage is 64 bits

Int64

In [188]:
Int8(a) # Changing precision of integer

2

In [189]:
Float64(a) # Changing an integers to a floating point number

2.0

In [190]:
typemin(Int8) # Minimum integer which can be defined with 8 bit precision

-128

In [191]:
typemax(Int64) # Maximum integer which can be defined with 64 bit precision

9223372036854775807

### Complex Numbers

In [192]:
c = Complex(a,b) # Making a complex numbers

Float16(2.0) + Float16(2.5)im

In [193]:
real(c) # extracting real part

Float16(2.0)

In [194]:
imag(c) # extracting imaginary part

Float16(2.5)

In [195]:
typeof(real(c)) #type of real part remains Float64

Float16

In [196]:
typeof(imag(c)) #type of imaginary part is upgraded to Float64 automatically

Float16

In [197]:
typeof(c) # The precision of complex number is 64 bits

Complex{Float16}

In [198]:
a = Complex(Inf,NaN) # COmpelx number with infinity as real part and NaN as imaginary part

Inf + NaN*im

In [199]:
a + Complex(2,3) # results as expected

Inf + NaN*im

### Complex algebra

In [200]:
conj(Complex(2,3)) # Conjugate

2 - 3im

In [201]:
abs(Complex(2,3)) # Absolute value

3.6055512754639896

In [202]:
sqrt(2^2+3^2) # calculated absolute value 

3.605551275463989

In [203]:
angle(Complex(2,3)) # Principle argument of acomplex number in radians

0.982793723247329

In [204]:
rad2deg(angle(Complex(2,3))) # Principle argument of acomplex number in radians

56.309932474020215

In [205]:
Complex(2,3) + Complex(1,2) # Add real parts and imaginary parts

3 + 5im

In [206]:
Complex(2,3) * Complex(1,2) # Multiplication of two complex numbers is valid mathematically

-4 + 7im

In [207]:
Complex(2,3) / Complex(1,2) # Division of two complex numbers is valid mathematically

1.6 - 0.2im

In [208]:
Complex(1,2)^Complex(2,3) # Complex number raised to the power of a complex number

-0.015132672422722664 - 0.17986748391333504im

### Rational Numbers

In [209]:
Rational(2,3) # Defining a rational number using 'Rational' function

2//3

In [210]:
2//3 # Defining a rational number using '//' operator

2//3

In [211]:
//(2,3) # Treating the symbol '//' as a function

2//3

In [212]:
numerator(2//3) # Numerator

2

In [213]:
denominator(2//3) # Denominator

3

In [214]:
0//0 # This is not defined mathematically

LoadError: ArgumentError: invalid rational: zero(Int64)//zero(Int64)

In [215]:
2//0 # This is not division by sero

1//0

In [216]:
2/0 #This is division by zero

Inf

In [217]:
0//2

0//1

#### Rational Algebra

In [218]:
1//3 + 2//3 # Addition results in a Rational type

1//1

In [219]:
println(1/3) # prints value of 1/3 as a floating point number
println(typeof(1//3)) # prints type of Rational number
println(typeof(1/3)) # prints type of answer valauted by expression 1/3

0.3333333333333333
Rational{Int64}
Float64


In [220]:
1//3 * 3//4 # 3//12 = 1//4

1//4

In [221]:
(1//2) / (2//3) # Division of a rational number

3//4

In [222]:
2^(1//2) # Rational numbers can be used as powers

1.4142135623730951

In [223]:
sqrt(2) # same as above

1.4142135623730951

In [224]:
(1//3)^2 # Powers of rational numbers can be defined with ease

1//9

In [225]:
(1//3)^(Complex(2,3)) # Rational number raised to a complex power!

-0.10979199190468789 + 0.017070369824541853im

In [226]:
a = Complex(2,3)


2 + 3im

In [227]:
b = Complex(3,4)

3 + 4im

In [228]:
Rational(a,b) # Can't be defined as division of two complex numbers is solved to result another complex number

LoadError: MethodError: no method matching Rational(::Complex{Int64}, ::Complex{Int64})

### Rational numbers to floating point numbers

In [229]:
Float16(1//3) # A rational number converted to flpation point number of defined precision

Float16(0.3333)

In [230]:
Float32(1//3) # Increased precision

0.33333334f0

In [231]:
Float64(1//3) # Even more increased precision

0.3333333333333333

In [232]:
Complex(1//3) # Rational number converted to a complex number (Imaginary part id zero)

1//3 + 0//1*im

In [233]:
Int64(1//3) # Precision loss error

LoadError: InexactError()

## Irrational Numbers

In [234]:
pi

π = 3.1415926535897...

In [235]:
e

e = 2.7182818284590...

Elipsis operator `...` signifies that digits do not end in this representation

In [236]:
typeof(pi)

Irrational{:π}

In [237]:
typeof(e)

Irrational{:e}

# Mathematical functions

## Division

In [238]:
a = div(3,5) # quotient
b = fld(3,5) # Floor division (towards -Inf)
c = cld(3,5) # Ciel division (towards +Inf)
println("div results $a, fld result $b, cld result $c") # Interploation of variable values

div results 0, fld result 0, cld result 1


In [239]:
3/5 # Answer results in a floating point number

0.6

In [240]:
rem(3,5) # Remainder is 3

3

In [241]:
rem(5,3) # Remainder is 2

2

In [242]:
q,r = divrem(5,3) # quoteint and remainder stored as a tuple

(1, 2)

In [243]:
gcd(5,7) # Greatest common divisior or primes is 1

1

In [244]:
lcm(5,10) # Least common multiple

10

## Power

In [245]:
sqrt(2) # square root

1.4142135623730951

In [246]:
cbrt(2) # cube root

1.2599210498948732

In [247]:
hypot(2,3) # Hypotenues = sqrt(2^2+3^2)

3.6055512754639896

In [248]:
exp(2) # exponentiation e^2

7.38905609893065

In [249]:
e^2 # e is predefined

7.38905609893065

In [250]:
log(e) # Natural logarithm (to the base of 'e')

1

In [251]:
log2(2) # Logarithm to the base 2

1.0

In [252]:
log10(10) # Logarithm to the base 10

1.0

## Trigonometric and Hyperbolic functions

In [253]:
a = sin(90)
b = sind(90)
c = cos(90)
d = cosd(90)
println("sin(90)=$a\tsind(90)=$b\ncos(90)=$c\tcosd(90)=$d") # \t print tab and \n prints newline

sin(90)=0.8939966636005579	sind(90)=1.0
cos(90)=-0.4480736161291702	cosd(90)=0.0


In [254]:
asind(sind(90)) # arcsin(sin(90))=90

90.0

In [255]:
sinh(90) # hyperbolic sin fucntion

6.102016471589204e38

In [256]:
asinh(sinh(90)) # arcsinh of sinh

90.0

# Matrix computations

## Elementwise

In [257]:
a = zeros(2,3);
b = ones(2,3);
c = a+b; # dimesnions should match
println("Matrix a is $a \n Matrix b is $b \n Sum of matrix a and b is $c")

Matrix a is [0.0 0.0 0.0; 0.0 0.0 0.0] 
 Matrix b is [1.0 1.0 1.0; 1.0 1.0 1.0] 
 Sum of matrix a and b is [1.0 1.0 1.0; 1.0 1.0 1.0]


In [258]:
2b # Elementwise multiplication

2×3 Array{Float64,2}:
 2.0  2.0  2.0
 2.0  2.0  2.0

In [259]:
2*b # * operator is option when defining multiplication when multiplier is a number

2×3 Array{Float64,2}:
 2.0  2.0  2.0
 2.0  2.0  2.0

In [260]:
2.5.^b # Elementwise operation of power operator (Similar to MATLAB)

2×3 Array{Float64,2}:
 2.5  2.5  2.5
 2.5  2.5  2.5

## Matrix Algebra

In [261]:
a = zeros(2,3)
b = ones(3,2)
a*b # Inner dimesnions must match (cross product)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [262]:
dot(a,b) # dot product

0.0

In [263]:
pinv(b) # Inverse of b (can use inv() function if argument is a square matrix)

2×3 Array{Float64,2}:
 0.166667  0.166667  0.166667
 0.166667  0.166667  0.166667

In [264]:
@time (b*pinv(b)) #profile time and storage for a particular evaluation

  0.000067 seconds (37 allocations: 11.969 KiB)


3×3 Array{Float64,2}:
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333